### ISSUE TITLE
It's returning 0 and 0?

### ISSUE THREAD

**Issue by GainoSaurus** [TheCruZ/CRZKD#3]
![image](https://user-images.githubusercontent.com/21149078/97782052-90e2fb80-1b8f-11eb-8028-c22ca4f9533d.png)

**Comment by TheCruZ** [comment]
I didn't take too much care in the return of the DeviceIoControls, in that case i normally simply check the base address != 0

**Comment by GainoSaurus** [comment]
Haven't been able to get it to work, not that good in converting c++ into c# but thanks for reply, currently asking help on UC https://www.unknowncheats.me/forum/c-/424413-read-pid-base_module.html
