### ISSUE TITLE
bsod

### ISSUE THREAD

**Issue by hadevn** [TheCruZ/CRZKD#4]
i got bsod when second times open usermode any idea to fix ? my winver 1909
`
int main()
{
    std::cout << "Hello World!\n";

     HANDLE driver = CreateFileW(
        L"\\\\.\\NsiLookup",
        GENERIC_ALL,
        FILE_SHARE_READ | FILE_SHARE_WRITE,
        nullptr,
        OPEN_EXISTING,
        FILE_ATTRIBUTE_NORMAL,
        nullptr
    );

    if (driver == INVALID_HANDLE_VALUE) {
        MessageBox(NULL, L"Can't open", L"Error", 0);
        return GetLastError();
    }

    const wchar_t* n = L"notepad.exe";

    PidBaseResponse result = { 0 };
    PidBase cmd2 = { 0 };
    memcpy(cmd2.name, n, wcslen(n) * sizeof(wchar_t));
    cmd2.RetInfoPid = (uintptr_t)&result.pid;
    cmd2.RetInfoAddr = (uintptr_t)&result.baseAddr;

    if (!DeviceIoControl(driver, GET_PID_AND_BASE, &cmd2, sizeof(PidBase), NULL, NULL, NULL, NULL)) {
        MessageBox(NULL, L"Unknown", L"Error", 0);
        return GetLastError();
    }
    printf("Base_Address:   %p\n", (uintptr_t)&result.baseAddr);
    system("pause");

    if (result.pid == 0) {
        MessageBox(NULL, L"No info received", L"Error", 0);
        return FALSE;
    }

}`

**Comment by TheCruZ** [comment]
The code is quite old, but I think that should work fine, but I don't remember at all it, you should check the BSOD file and check the exception point with WinDbg
