### ISSUE TITLE
doesent work

### ISSUE THREAD

**Issue by Acra1337** [TheCruZ/CRZKD#5]
1st run - No info received
2nd run - BSOD SYSTEM_SERVICE_EXCEPTION
win10

`#include <Windows.h>
#include  <iostream>
#include <conio.h>

#define REQUEST_READ_WRITE CTL_CODE(FILE_DEVICE_UNKNOWN, 0x826, METHOD_OUT_DIRECT, FILE_ANY_ACCESS) //YOU MUST CHANGE IOCTL CODE
#define GET_PID_AND_BASE CTL_CODE(FILE_DEVICE_UNKNOWN, 0x827, METHOD_OUT_DIRECT, FILE_ANY_ACCESS) //YOU MUST CHANGE IOCTL CODE

typedef struct PidBase
{
    wchar_t name[200];
    uintptr_t RetInfoPid;
    uintptr_t RetInfoAddr;
} PidBase;
struct PidBaseResponse {
    unsigned long long pid;
    unsigned long long baseAddr;

};
void main() {

    HANDLE driver = CreateFile(
        L"\\\\.\\NsiLookup",
        GENERIC_ALL,
        FILE_SHARE_READ | FILE_SHARE_WRITE,
        nullptr,
        OPEN_EXISTING,
        FILE_ATTRIBUTE_NORMAL,
        nullptr
    );

    if (driver == INVALID_HANDLE_VALUE) {
        MessageBox(NULL, L"Can't handle", L"Error", 0);
        return;
    }

    const wchar_t* n = L"Explorer.exe";

    PidBaseResponse result = { 0 };
    PidBase cmd2 = { 0 };
    memcpy(cmd2.name, n, wcslen(n) * sizeof(wchar_t));
    cmd2.RetInfoPid = (uintptr_t)&result.pid;
    cmd2.RetInfoAddr = (uintptr_t)&result.baseAddr;

    if (!DeviceIoControl(driver, GET_PID_AND_BASE, &cmd2, sizeof(PidBase), NULL, NULL, NULL, NULL)) {
        MessageBox(NULL, L"Unknown", L"Error", 0);
        return;
    }

    if (result.pid == 0) {
        MessageBox(NULL, L"No info received", L"Error", 0);
        return;
    }
}`

**Comment by Acra1337** [comment]
I assuming the cause is cleaner as soon as i documented it so and the bsod did not fly out and the pid gave out.
![image](https://user-images.githubusercontent.com/91015718/224270701-e1fb1f15-977e-4299-b428-62cb155af2cc.png)

**Comment by TheCruZ** [comment]
Is a simple project with my firsts ioctl usages improvements or a good code isn't spected, the cleaner just fill with CC functions that will not be used anymore but calculates size by function location and the compiler can modify this order easily

**Comment by hern0s-dev** [comment]
> Is a simple project with my firsts ioctl usages improvements or a good code isn't spected, the cleaner just fill with CC functions that will not be used anymore but calculates size by function location and the compiler can modify this order easily

Just disable compiler optimization from project settings.
